#
# Complete config docs in https://github.com/BloodLetters/AsAntiVpn-Document/wiki/AsAntiVpn-Setup
#

Key:
  ProxyCheck: ""
  VpnApi: ""
  IpHub: ""
  GetIPIntel: "" # Placeyour email

Discord:
  Enable: false
  Link: ""
# To use this place your Discord Webhook in Link: "Here"
# to get Discord webhook
# 1). go to channel integration of your discord channel
# 2). Click on view Webhook
# 3). new webhook and click "Copy webhook url"
# 4). place to Link: "Here"

Whitelist-IP:
  - 127.0.0.1
# place this you want to whitelist!

Whitelist-Player:
  - derp
  - coolestderp
# place your staff name in here

Kick-Algorithm:
  Slow-Join-Tick: 5
  Show-API-name-onjoin: false

Message:
  # permission & Command
  NoPermission: "&7[&c!&7] &cSorry you dont have accesss"
  Blacklist:
    Ip-Add: "&cIncorrect CMD!. example: &a/AsAntiVpn add 1.1.1.1"
    Ip-Add-Success: "&aSuccess to add &e%player-ip%"
    Ip-Remove: "&cIncorrect CMD!. example: &a/AsAntiVpn remove 1.1.1.1"
    Ip-Remove-Success: "&aSuccess to remove &e%player-ip%"
  Inspect: "&cIncorrect CMD!. example: &a/AsAntiVpn inspect titidsapi"
  Check-ip: "&cIncorrect CMD!. example: &a/AsAntiVpn check 1.2.3.4"

  # kick message.
  Kick-Message: "&7[&c!&7] &cDont use vpn!"
  Blacklist-Message: "&7[&c!&7] &cSorry your ip has blocked from this server!"
  Whitelist-player-Message: "%player% Bypass AntiVpn from config!"
  Whitelist-ip-Message: "%player-ip% Bypass AntiVpn from config!"
  Country-Blacklist: "&7[&c!&7] &cSorry your country not allowed in this server!"

  # api error message
  Api-Limit: "&7Api cant detect player ip %player-ip% because got limit. wait 1 minute until reset"
  Api-usgae-Limit: "Max Api usage has reached. Api Reset 00:00 UTC"