#
# Complete config docs in https://github.com/BloodLetters/AsAntiVpn-Document/wiki/AsAntiVpn-Setup
#

Key:
  ProxyCheck: ""
  VpnApi: ""
  IpHub: ""
  GetIPIntel: ""

Discord:
  Enable: false
  Link: ""

Whitelist-IP:
  - 127.0.0.1

Whitelist-Player:
  - derp
  - coolestderp

Hide-message:
  Added-to-blacklist: false
  Hide-blacklist-when-join: false

Kick-Algorithm:
  Use-Algorithm: 3
  Show-API-name-onjoin: false
  Execute-command-when-kicked:
    Enable: false
    Command: "" # executed by console, dont put slash("/")
# Check the docs for more information!.

Message:
  # permission & Command
  NoPermission: "&7[&c!&7] &cSorry you dont have accesss"
  Blacklist:
    Ip-Add: "&cIncorrect CMD!. example: &a/AsAntiVpn add 1.1.1.1"
    Ip-Add-Success: "&aSuccess to add &e%player-ip%"
    Ip-Remove: "&cIncorrect CMD!. example: &a/AsAntiVpn remove 1.1.1.1"
    Ip-Remove-Success: "&aSuccess to remove &e%player-ip%"
  Inspect: "&cIncorrect CMD!. example: &a/AsAntiVpn inspect titidsapi"
  Check-ip: "&cIncorrect CMD!. example: &a/AsAntiVpn check 1.2.3.4"

  # kick message.
  Kick-Message: "&7[&c!&7] &cDont use vpn!"
  Kick-Message-Console: "&7[&eNotify&7] &b%player% &cKicked because detected using VPN"
  Blacklist-Message: "&7[&c!&7] &cSorry your ip has blocked from this server!"
  Blacklist-Console-Message: "%player% tried to join but the ip has been blocked in Blacklist.yml"
  Whitelist-player-Message: "%player% Bypass AntiVpn from config!"
  Whitelist-ip-Message: "%player-ip% Bypass AntiVpn from config!"


  # api error message
  Api-Limit: "&7Api cant detect player ip %player-ip% because got limit. wait 1 minute until reset"
  Api-usgae-Limit: "Max Api usage has reached. Api Reset 00:00 UTC"