name: AsAntiVpn
version: '${project.version}'
main: me.bl.main
api-version: 1.18
authors: [ Aril4511 ]
description: Simple lightweight Anti Vpn!
softdepend:
  - PlaceholderAPI
commands:
  AsAntiVpn:
    permission: asantivpn.use